[project]
name = "monorepo-dagger"
version = "0.1.0"
requires-python = ">=3.13.1"
dependencies = [
    "dagger-io",
    "tomli>=2.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
